[workspace]
members = ["mob", "spawner"]

[package]
name = "root"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mob"
path = "mob/src/main.rs"

[[bin]]
name = "spawner"
path = "spawner/src/main.rs"


[dependencies]
# mineraft-core = { path = "./mineraft-core" }
